name: drivers_license_parser
description: This package provides a simple and effective utility for parsing barcodes displayed on the back of drivers license cards issued in the United States and Canada.
version: 1.2.2
homepage: https://github.com/axlehire/drivers_license_parser

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
